/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author JOSE3
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
    }
    String numero1="";
    String numero2="";
    int contador=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        division = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        etiqueta1 = new javax.swing.JLabel();
        etiqueta2 = new javax.swing.JLabel();
        etiqueta3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        num7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num7.setText("7");
        num7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });
        getContentPane().add(num7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 40, 40));

        num8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num8.setText("8");
        num8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        getContentPane().add(num8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 40, 40));

        num9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num9.setText("9");
        num9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        getContentPane().add(num9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 40, 40));

        num4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num4.setText("4");
        num4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        getContentPane().add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 40, 40));

        num5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num5.setText("5");
        num5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        getContentPane().add(num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 40, 40));

        num6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num6.setText("6");
        num6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });
        getContentPane().add(num6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 40, 40));

        num1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num1.setText("1");
        num1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        getContentPane().add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 40, 40));

        num2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num2.setText("2");
        num2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        getContentPane().add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 40, 40));

        num3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num3.setText("3");
        num3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        getContentPane().add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 40, 40));

        num0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num0.setText("0");
        num0.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        getContentPane().add(num0, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 40, 40));

        punto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        punto.setText(".");
        punto.setMargin(new java.awt.Insets(2, 2, 2, 2));
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });
        getContentPane().add(punto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 40, 40));

        borrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        borrar.setText("C");
        borrar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        getContentPane().add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 40, 40));

        menos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menos.setText("-");
        menos.setMargin(new java.awt.Insets(2, 2, 2, 2));
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });
        getContentPane().add(menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 40, 40));

        mas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mas.setText("+");
        mas.setMargin(new java.awt.Insets(2, 2, 2, 2));
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });
        getContentPane().add(mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 40, 40));

        division.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        division.setText("/");
        division.setMargin(new java.awt.Insets(2, 2, 2, 2));
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });
        getContentPane().add(division, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 40, 40));

        multiplicacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        multiplicacion.setText("*");
        multiplicacion.setMargin(new java.awt.Insets(2, 2, 2, 2));
        multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(multiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 40, 40));

        igual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        igual.setText("=");
        igual.setMargin(new java.awt.Insets(2, 2, 2, 2));
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });
        getContentPane().add(igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 192, 40));

        etiqueta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 115, 40));

        etiqueta2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiqueta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 115, 40));

        etiqueta3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiqueta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiqueta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 115, 40));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 168, 287));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        numero1 += "0";
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num0ActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
       numero1 += "1";
       etiqueta3.setText(numero1);
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        numero1 += "2";
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        numero1 += "3";
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        numero1 += "4";
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        numero1 += "5";
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        numero1 += "6";
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        numero1 += "7";
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        numero1 += "8";
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        numero1 += "9";
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num9ActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        numero1 = "";
        numero2 = "";
        etiqueta1.setText("");
        etiqueta2.setText("");
        etiqueta3.setText("");
        contador=0;
    }//GEN-LAST:event_borrarActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        if(!etiqueta3.getText().equals("")||contador !=0){
            operaciones();
            etiqueta2.setText("/");
        }  
    }//GEN-LAST:event_divisionActionPerformed

    private void multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacionActionPerformed
        if(!etiqueta3.getText().equals("")||contador !=0){
            operaciones();
            etiqueta2.setText("*");
        }
    }//GEN-LAST:event_multiplicacionActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        if(!etiqueta3.getText().equals("")||contador !=0){
            operaciones();
            etiqueta2.setText("-");
        }
    }//GEN-LAST:event_menosActionPerformed

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
        if(!etiqueta3.getText().equals("")||contador !=0){
            operaciones();
            etiqueta2.setText("+");
        }
    }//GEN-LAST:event_masActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        if(!etiqueta3.getText().equals("")||contador !=0){
            operaciones();
            etiqueta2.setText("");
        }
    }//GEN-LAST:event_igualActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        numero1 += ".";
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_puntoActionPerformed
    
    void operaciones(){
        double n1,n2;
        if(!etiqueta3.getText().equals("")){
            if(contador == 0){
                numero2 = numero1;
                etiqueta2.setText(numero2);
            }
            if(numero2.equals("")){
                numero2 = "0";
            }
            n1=Double.valueOf(numero2);
            n2=Double.valueOf(numero1);
            if(etiqueta2.getText().equals("-")){
                numero2 = String.valueOf(n1-n2);
            }
            if(etiqueta2.getText().equals("+")){
                numero2 = String.valueOf(n1+n2);
            }
            if(etiqueta2.getText().equals("*")){
                numero2 = String.valueOf(n1*n2);
            }
            if(etiqueta2.getText().equals("/")){
                numero2 = String.valueOf(n1/n2);
            }
            etiqueta3.setText("");
            numero1 = "";
            contador++;
            etiqueta1.setText(numero2);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton division;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JLabel etiqueta3;
    private javax.swing.JButton igual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mas;
    private javax.swing.JButton menos;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton punto;
    // End of variables declaration//GEN-END:variables
}
